include("DataReader.jl")
include("DataWriter.jl")
include("DistanceMatrix.jl")
include("UPGMA.jl")
include("ProgressiveAligment/ProgressiveAlignment.jl")
include("UPGMA2.jl")
include("ProgressiveAligment/ProgressiveAlignment2.jl")    