include("DataReader.jl")
include("DataWriter.jl")
include("DistanceMatrix.jl")
include("ProgressiveAlignment/ProgressiveAlignment.jl")
include("UPGMA2.jl")
include("ProgressiveAlignment/ProgressiveAlignment2.jl")    
